### ISSUE TITLE
Vulnerabilities Galore

### ISSUE THREAD

**Issue by sid-newby** [karfly/chatgpt_telegram_bot#150]
https://dso.docker.com/cve/CVE-2022-40897

**Comment by troyxmccall** [comment]
just swap your local copy to run a alpine image like this in your `Dockerfile`




```Dockerfile
# Use an official Python runtime as a parent image
FROM python:3.11-alpine as builder

# Set environment variables
ENV PYTHONFAULTHANDLER=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONHASHSEED=random \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100

# Install necessary packages and create code directory
RUN apk add --no-cache build-base && \
    mkdir -p /code

# Set the working directory to /code
WORKDIR /code

# Copy the current directory contents into the container at /code
COPY . /code/

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Final stage to keep only necessary files and dependencies
FROM python:3.11-alpine

# Install necessary libraries for ffmpeg
RUN apk add --no-cache libgcc libstdc++ musl ffmpeg

# Copy necessary files and dependencies from builder stage
COPY --from=builder /usr/local/lib/python3.11/site-packages/ /usr/local/lib/python3.11/site-packages/
COPY --from=builder /usr/lib/ /usr/lib/
COPY --from=builder /code/ /code/

# Set the working directory to /code
WORKDIR /code

# Set environment variables
ENV PYTHONFAULTHANDLER=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONHASHSEED=random \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100

# Run the command when the container launches
CMD ["bash"]
```



and if you're that worried about security, i'd turn off port-mapping on your host, and make sure your project is using it's own internal network in `docker-compose.yml`  bc any mongo image is gonna have a long list of vulnerabilities 

```yaml
version: "3"

services:
  mongo:
    container_name: mongo
    # use a production friendly mongo image
    image: bitnami/mongodb:latest
    restart: always
    # comment out host port mapping
    # ports:
    #   - "${MONGODB_PORT:-27017}:${MONGODB_PORT:-27017}"
    volumes:
      - "${MONGODB_PATH:-./mongodb}:/data/db"
    networks:
      - gpt_internal_network
    # TODO: add auth

  chatgpt_telegram_bot:
    container_name: chatgpt_telegram_bot
    command: python3 bot/bot.py
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    depends_on:
      - mongo
    networks:
      - gpt_internal_network

  mongo_express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: always
    # comment out host port mapping
    # ports:
    #   - "${MONGO_EXPRESS_PORT:-8081}:${MONGO_EXPRESS_PORT:-8081}"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=${MONGODB_PORT:-27017}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=chatgpt_telegram_bot
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME:-username}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD:-password}
    depends_on:
      - mongo
    networks:
      - gpt_internal_network

networks:
  gpt_internal_network:
```
