### ISSUE TITLE
Allowed usernames

### ISSUE THREAD

**Issue by cookins** [karfly/chatgpt_telegram_bot#329]
Hey again.
Wanna all about allowed usernames. So i editing file config.yml, to be exact: "allowed_telegram_usernames: [name1, name2]"
But my name isn't there and i still can chat with bot (I'm owner of bot). Is this feature working as it should?

**Comment by cookins** [comment]
> Hi!
> Only users presented in `allowed_telegram_usernames` are able to chat with bot. Did you rerun the bot after changing the config?

Yup

**Comment by karfly** [comment]
Yes, for example: `allowed_telegram_usernames: ["@karfly", "@cookins"]`

**Comment by cookins** [comment]
> Yes, for example: `allowed_telegram_usernames: ["@karfly", "@cookins"]`

![IMG_20230713_191343.jpg](https://github.com/karfly/chatgpt_telegram_bot/assets/7893051/043d08da-00ba-45a4-8fac-1aa35466e94a)

I still can pm bot and chat with it. After changes - i rebooted vps. For some reason - it not works. Maybe, cuz I'm owner of bot?

**Comment by AyvazovAleksandr** [comment]
> Да, например: `allowed_telegram_usernames: ["@karfly", "@cookins"]`

Good evening. So now ID or nicknames should be specified in this field?

**Comment by karfly** [comment]
@cookins 
🤔 Can't understand, why it doesn't work. Code (file bot.py, line 675) is pretty straightforward

**Comment by karfly** [comment]
@AyvazovAleksandr
If you pass strings – they be treated as usernames 
If ints – they will be treated as group_id/group_ids

**Comment by gin063** [comment]
> > Yes, for example: `allowed_telegram_usernames: ["@karfly", "@cookins"]`
> 
> Hello @karfly , I have a question, if I wanna add a specific username and a group id, what is the correct format to write on the following line? allowed_telegram_usernames: ["@username", "-123456"] Is this right?

Solved, no double quotation marks "".
ask https://t.me/username_to_id_bot to get your user id and chat id.
allowed_telegram_usernames: [123456, -123456]

**Comment by kimberk** [comment]
example;
allowed_telegram_usernames: ["@yazgulu","@aldogan",18526095,1354409621,"@saksak"]

Im not sure group id is not allowed.

**Comment by cookins** [comment]
> @cookins 
> 🤔 Can't understand, why it doesn't work. Code (file bot.py, line 675) is pretty straightforward 

Sorry

**Comment by gin063** [comment]
> > @cookins
> > 🤔 Can't understand, why it doesn't work. Code (file bot.py, line 675) is pretty straightforward
> 
> Sorry to ask. I figured what was that issue. I'm not restarted bot... of course. But can you tell me, what i doing wrong (kinda still learning with docker) - i restarted server, i restarted containers (with new config).... but it still on old config.. maybe data from config.yml written to mongo db and i need to clean db? Or should i fully recompose with docker (but its not overwrite too and config still old)? ![IMG_20230805_192657.jpg](https://user-images.githubusercontent.com/7893051/258596804-9c3385fd-38a8-46d4-8eba-ec2ba0c69d00.jpg)

after you changed your config files, do the following steps.

list containers: docker ps
stop container: docker stop name
remove container: docker rm name
list images: docker images -a
remove image: docker image rm name
change directory to the config file folder: cd /path/path
recreate image: docker compose --env-file config/config.env up --build

**Comment by cookins** [comment]
> after you changed your config files, do the following steps.
> 
> list containers: docker ps
> stop container: docker stop name
> remove container: docker rm name
> list images: docker images -a
> remove image: docker image rm name
> change directory to the config file folder: cd /path/path
> recreate image: docker compose --env-file config/config.env up --build

Yeah, "rerun" bot is not correct answer, but "recompose" - is.
I made it even simpler -
`docker-compose ps
docker-compose stop chatgpt_telegram_bot
docker-compose rm chatgpt_telegram_bot
docker-compose build chatgpt_telegram_bot
docker-compose up -d`

**Comment by karfly** [comment]
Nice!

**Comment by azazar** [comment]
It's more convenient to bind mount `config` volume into the continer:

```
version: "3"

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - 127.0.0.1:${MONGODB_PORT:-27017}:${MONGODB_PORT:-27017}
    volumes:
      - ${MONGODB_PATH:-./mongodb}:/data/db
    # TODO: add auth

  chatgpt_telegram_bot:
    container_name: chatgpt_telegram_bot
    command: python3 bot/bot.py
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    depends_on:
      - mongo
    volumes:
      - ./config:/code/config

  mongo_express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: always
    ports:
      - 127.0.0.1:${MONGO_EXPRESS_PORT:-8081}:${MONGO_EXPRESS_PORT:-8081}
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=${MONGODB_PORT:-27017}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=chatgpt_telegram_bot
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME:-username}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD:-password}
    depends_on:
      - mongo
```
