### ISSUE TITLE
error

### ISSUE THREAD

**Issue by lijingbo666** [karfly/chatgpt_telegram_bot#74]
Service 'chatgpt_telegram_bot' failed to build: The command '/bin/sh -c apt-get install -y python3 python3-pip python-dev build-essential python3-venv' returned a non-zero code: 100

**Comment by Andy963** [comment]
need more info about your system, the apt-get install work on system like ubuntu but not centos..

**Comment by lijingbo666** [comment]
ubunto Ubuntu 20.04 64位 Linux 64位

**Comment by Li-Yaoting** [comment]
i have the same problem.
![image](https://user-images.githubusercontent.com/54201517/222783662-d10299df-ccf3-4cb7-a19d-a90517bb1984.png)

**Comment by wy580477** [comment]
I have built a ready-to-use image for x86_64: 

ghcr.io/wy580477/chatgpt_telegram_bot:latest

https://github.com/wy580477/chatgpt_telegram_bot/tree/custom

You need to mount a config.yml to container:

```
version: "3"

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - ./mongodb:/data/db
    # TODO: add auth

  chatgpt_telegram_bot:
    container_name: chatgpt_telegram_bot
    image: ghcr.io/wy580477/chatgpt_telegram_bot:latest
    restart: unless-stopped
    volumes:
      - ./config.yml:/code/config/config.yml
    depends_on:
      - mongo
```
